/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoundationCheckRouteImport } from './routes/foundation.check'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationCheckRoute = FoundationCheckRouteImport.update({
  id: '/foundation/check',
  path: '/foundation/check',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foundation/check': typeof FoundationCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foundation/check': typeof FoundationCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foundation/check': typeof FoundationCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/foundation/check'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/foundation/check'
  id: '__root__' | '/' | '/foundation/check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoundationCheckRoute: typeof FoundationCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation/check': {
      id: '/foundation/check'
      path: '/foundation/check'
      fullPath: '/foundation/check'
      preLoaderRoute: typeof FoundationCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoundationCheckRoute: FoundationCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
